# Generated by Django 3.2.9 on 2022-03-12 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40)),
                ('bio', models.CharField(blank=True, max_length=150)),
                ('profile_pic', models.FileField(blank=True, upload_to='profile_pics')),
                ('followers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_followers', to='user_app.account')),
                ('following', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_following', to='user_app.account')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
