# Generated by Django 3.2.9 on 2022-03-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='media',
        ),
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.ManyToManyField(to='main_app.Media'),
        ),
    ]
