# Generated by Django 3.2.9 on 2022-03-12 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20220313_0016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
