# Generated by Django 3.2.9 on 2022-03-12 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20220313_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_like',
            name='account',
        ),
        migrations.RemoveField(
            model_name='comment_like',
            name='comment',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Comment_like',
        ),
    ]
